--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster
  region: eu-north-1
managedNodeGroups:
  - name: workers
    privateNetworking: false
    instanceType: t3.small
    desiredCapacity: 2
    labels:
      role: workers
