---
metadata:
  name: FubarProduction
  region: us-east-1
managedNodeGroups:
  - name: workers
    privateNetworking: true
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
